<?php
/**
 * Product:     Advanced Permissions
 * Package:     Aitoc_Aitpermissions_2.3.13_2.0.3_462149
 * Purchase ID: JlNeBKBvSqsIsT7whc80ZpBA38zH86mwW38f4D7p5H
 * Generated:   2012-12-18 08:22:46
 * File path:   app/design/frontend/default/default/template/aitpermissions/lfooter.phtml
 * Copyright:   (c) 2012 AITOC, Inc.
 */
?>
<?php
/**
 * @copyright  Copyright (c) 2009 AITOC, Inc. 
 */
?>
<!-- wuxlrjlosekakwsuhtmvnhicqzyzwjos -->