<link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/redmond/jquery-ui.css" rel="stylesheet" type="text/css"/> 
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script>
function open_win()
{
window.open("http://gentingtravel.starcruises.com")
}</script>

<?php 
	$offset = Mage::getStoreConfig('custom/cruise_pickup/days_count');
	if($offset == ""){
		$currDate = "+1d";
	}else{
		$currDate = "+".$offset."d";
	}
?>
<form id="co-heared4us-form" action="">

	<script>
	jQuery(function() {
		jQuery('.datepick').datepicker({
			changeMonth: true,
			changeYear: true,
			maxDate: '+3m',
			minDate: '<?php echo $currDate?>'
		});
	});jQuery.noConflict();
	</script>
	
<?php 
	$checkoutSession = Mage::getSingleton('checkout/session');	
	$cstmOptions = Mage::getSingleton('custom/pickupoptions');	
		
	Mage::getSingleton('core/session', array('name'=>'frontend'));	
	
	$store= $cstmOptions->getPickupData();	
	
	$pickupCounter = 1;
?>
	
	<?php foreach($store as $pickupLocation => $value) : ?>
	
		<?php $pickupLocationInfo = $cstmOptions->getStoreLocationByValue($pickupLocation);  ?>
		
		<ul class="form-list">
			<li class="fields">
				<div class="field">
					<label for="pickup" style="margin-top: 5px">Items: </label>
					<div class="input-box">
					
						<?php foreach($value as $item) : ?>						
							<p style="margin: 0px"><?php echo $item[1] . " " . $item[0];?></p>						
						<?php endforeach; ?>
						
					</div>
					
					<?php if( $cstmOptions->getStoreAttributeLocationType($pickupLocation) == Movent_Custom_Model_Pickupoptions::LOCATION_TYPE_CRUISE) : ?>
						<label for="pickup" style="margin-top: 5px"><?php echo $this->__('To be picked up onboard') ?>: </label>
					<?php else: ?>
						<label for="pickup" style="margin-top: 5px"><?php echo $this->__('To be picked up at') ?>: </label>
					<?php endif; ?>
					
    				
		    		<div class="input-box">
						<p style="margin: 0px"><?php echo $pickupLocationInfo['label']?></p>
					</div>
				</div>
			</li>
			<li class="fields">
		    	<div class="field">
				
					<?php if( $cstmOptions->getStoreAttributeLocationType($pickupLocation) == Movent_Custom_Model_Pickupoptions::LOCATION_TYPE_CRUISE) : ?>
						<label for="cruise-date-<?php echo $pickupCounter?>" class="required"><em>*</em><?php echo $this->__('Your cruise date')?>:</label>
					<?php else: ?>
						<label for="cruise-date-<?php echo $pickupCounter?>" class="required"><em>*</em><?php echo $this->__('Your Pickup date')?>:</label>
					<?php endif; ?>
					
					<div class="input-box">
						<input type="text" class="datepick input-text required-entry" style="border-color: #DDDDDD; cursor: pointer" readonly="readonly" id="cruise-date-<?php echo $pickupCounter?>" name="cruise-date-<?php echo $pickupCounter?>"/>
						<input type="hidden" id="pickup-location-<?php echo $pickupCounter?>" name="pickup-location-<?php echo $pickupCounter?>" value="<?php echo $pickupLocationInfo['value']?>"/>
						<input type="hidden" id="pickup-counter" name="pickup-counter" value="<?php echo $pickupCounter?>"/>
					</div>
				</div>
			</li>	
		</ul>
		<div class="form-list" style="width:300px;float:left;">
					<label for="cruise-reservation-number-<?php echo $pickupCounter?>"><?php echo $this->__('Cruise Reservation Number:')?></label>
					<div class="input-box">
						<input type="text" id="cruise-reservation-number-<?php echo $pickupCounter?>"  name="cruise-reservation-number[<?php echo $pickupCounter?>]" value="<?php echo $this->getCruiseReservationNumber($pickupCounter);?>"/>
					</div>
		</div>
		<div>No cruise booking yet?</div>
		<div><a href="javascript:void(0);" onclick="open_win()">Book Now</a> and get instant confirmation online.</div> 
		<hr> 
	<?php $pickupCounter++; endforeach; ?>


</form>

<div class="buttons-set" id="heared4us-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="heared4us.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="opc-please-wait" id="heared4us-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
</div>


<script type="text/javascript">
//<![CDATA[

var Heared4us = Class.create();
Heared4us.prototype = {
    initialize: function(form, saveUrl){
        this.form = form;
        if ($(this.form)) {
            $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
        }
        this.saveUrl = saveUrl;
        this.onSave = this.nextStep.bindAsEventListener(this);
        this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
    },

    save: function(){
        if (checkout.loadWaiting!=false) return;

        var validator = new Validation(this.form);
        if (validator.validate()) {

            checkout.setLoadWaiting('heared4us');


            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    resetLoadWaiting: function(transport){
        checkout.setLoadWaiting(false);
    },

    nextStep: function(transport){
        if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
            if ((typeof response.message) == 'string') {
                alert(response.message);
            } else {
                if (window.billingRegionUpdater) {
                    billingRegionUpdater.update();
                }

                alert(response.message.join("\n"));
            }

            return false;
        }

        checkout.setStepResponse(response);
    }    
}

var heared4us = new Heared4us('co-heared4us-form', '<?php echo $this->getUrl('checkout/onepage/saveHeared4us') ?>');

//]]>
</script>